extern const GeoLayout soap_bar_geo[];
extern Lights1 soap_bar_Material_0_f3d_lights;
extern Lights1 soap_bar_Material_1_f3d_lights;
extern u8 soap_bar__0_rgba16[];
extern u8 soap_bar__1_rgba32[];
extern Vtx soap_bar_node_mesh_layer_1_vtx_cull[8];
extern Vtx soap_bar_node_mesh_layer_1_vtx_0[43];
extern Gfx soap_bar_node_mesh_layer_1_tri_0[];
extern Vtx soap_bar_node_mesh_layer_5_vtx_cull[8];
extern Vtx soap_bar_node_mesh_layer_5_vtx_0[4];
extern Gfx soap_bar_node_mesh_layer_5_tri_0[];
extern Gfx mat_soap_bar_Material_0_f3d[];
extern Gfx mat_soap_bar_Material_1_f3d[];
extern Gfx mat_revert_soap_bar_Material_1_f3d[];
extern Gfx soap_bar_node_mesh_layer_1[];
extern Gfx soap_bar_node_mesh_layer_5[];
