extern const GeoLayout custom_ttc_rotating_clockwise_gear_geo[];
extern Lights1 custom_ttc_rotating_clockwise_gear_Material_0_f3d_lights;
extern u8 custom_ttc_rotating_clockwise_gear__0_rgba16[];
extern Vtx custom_ttc_rotating_clockwise_gear_node_mesh_layer_1_vtx_cull[8];
extern Vtx custom_ttc_rotating_clockwise_gear_node_mesh_layer_1_vtx_0[20];
extern Gfx custom_ttc_rotating_clockwise_gear_node_mesh_layer_1_tri_0[];
extern Gfx mat_custom_ttc_rotating_clockwise_gear_Material_0_f3d[];
extern Gfx custom_ttc_rotating_clockwise_gear_node_mesh_layer_1[];
