extern const GeoLayout pipe_cover_geo[];
extern Lights1 pipe_cover_Material_0_003_f3d_lights;
extern u8 pipe_cover__0_rgba16[];
extern Vtx pipe_cover_Blue_Pipe_Cover_mesh_layer_4_vtx_cull[8];
extern Vtx pipe_cover_Blue_Pipe_Cover_mesh_layer_4_vtx_0[4];
extern Gfx pipe_cover_Blue_Pipe_Cover_mesh_layer_4_tri_0[];
extern Gfx mat_pipe_cover_Material_0_003_f3d[];
extern Gfx mat_revert_pipe_cover_Material_0_003_f3d[];
extern Gfx pipe_cover_Blue_Pipe_Cover_mesh_layer_4[];
extern Gfx pipe_cover_material_revert_render_settings[];
