extern const GeoLayout star_w7_geo[];
extern Lights1 star_w7_Eye_lights;
extern u8 star_w7_star_surface_world_7_rgba16[];
extern u8 star_w7_star_eye_rgba16[];
extern Vtx star_w7_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx star_w7_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx star_w7_001_displaylist_mesh_layer_5_vtx_0[8];
extern Gfx star_w7_001_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_star_w7_Surface[];
extern Gfx mat_revert_star_w7_Surface[];
extern Gfx mat_star_w7_Eye[];
extern Gfx star_w7_000_displaylist_mesh_layer_1[];
extern Gfx star_w7_001_displaylist_mesh_layer_5[];
