extern const GeoLayout ddd_purple_appearing_path_geo[];
extern Lights1 ddd_purple_appearing_path_Material_0_f3d_lights;
extern u8 ddd_purple_appearing_path__0_rgba16[];
extern Vtx ddd_purple_appearing_path_node_mesh_layer_1_vtx_cull[8];
extern Vtx ddd_purple_appearing_path_node_mesh_layer_1_vtx_0[8];
extern Gfx ddd_purple_appearing_path_node_mesh_layer_1_tri_0[];
extern Gfx mat_ddd_purple_appearing_path_Material_0_f3d[];
extern Gfx ddd_purple_appearing_path_node_mesh_layer_1[];
