extern const GeoLayout smash_bros_metal_geo[];
extern Lights1 smash_bros_metal_Material_0_f3d_lights;
extern u8 smash_bros_metal__0_ci4[];
extern u8 smash_bros_metal__0_pal_rgba16[];
extern Vtx smash_bros_metal_node_mesh_layer_1_vtx_cull[8];
extern Vtx smash_bros_metal_node_mesh_layer_1_vtx_0[104];
extern Gfx smash_bros_metal_node_mesh_layer_1_tri_0[];
extern Gfx mat_smash_bros_metal_Material_0_f3d[];
extern Gfx mat_revert_smash_bros_metal_Material_0_f3d[];
extern Gfx smash_bros_metal_node_mesh_layer_1[];
