extern const GeoLayout purple_pendulum_geo[];
extern Lights1 purple_pendulum_Material_0_f3d_lights;
extern Lights1 purple_pendulum_Material_1_f3d_lights;
extern u8 purple_pendulum__0_rgba16[];
extern u8 purple_pendulum__1_rgba16[];
extern Vtx purple_pendulum_node_mesh_layer_1_vtx_cull[8];
extern Vtx purple_pendulum_node_mesh_layer_1_vtx_0[40];
extern Gfx purple_pendulum_node_mesh_layer_1_tri_0[];
extern Vtx purple_pendulum_node_mesh_layer_1_vtx_1[24];
extern Gfx purple_pendulum_node_mesh_layer_1_tri_1[];
extern Gfx mat_purple_pendulum_Material_0_f3d[];
extern Gfx mat_purple_pendulum_Material_1_f3d[];
extern Gfx purple_pendulum_node_mesh_layer_1[];
