extern const GeoLayout super_bell_geo[];
extern Lights1 super_bell__147_273FF6_c_bmp_f3d_lights;
extern Lights1 super_bell__181_3294D28F_c_bmp_f3d_lights;
extern u8 super_bell__273FF6_c_rgba16[];
extern u8 super_bell_Super_Bell_Eyes_rgba16[];
extern Vtx super_bell_Bell_mesh_layer_1_vtx_0[128];
extern Gfx super_bell_Bell_mesh_layer_1_tri_0[];
extern Vtx super_bell_Bell_mesh_layer_5_vtx_0[6];
extern Gfx super_bell_Bell_mesh_layer_5_tri_0[];
extern Gfx mat_super_bell__147_273FF6_c_bmp_f3d[];
extern Gfx mat_super_bell__181_3294D28F_c_bmp_f3d[];
extern Gfx super_bell_Bell_mesh_layer_1[];
extern Gfx super_bell_Bell_mesh_layer_5[];
