extern const GeoLayout straight_mushroom_geo[];
extern Lights1 straight_mushroom_Material_0_f3d_lights;
extern Lights1 straight_mushroom_Material_1_f3d_lights;
extern Lights1 straight_mushroom_Material_2_f3d_lights;
extern u8 straight_mushroom__0_rgba16[];
extern u8 straight_mushroom__1_rgba16[];
extern u8 straight_mushroom__2_rgba16[];
extern Vtx straight_mushroom_Bone_mesh_layer_1_vtx_0[126];
extern Gfx straight_mushroom_Bone_mesh_layer_1_tri_0[];
extern Vtx straight_mushroom_Bone_mesh_layer_1_vtx_1[60];
extern Gfx straight_mushroom_Bone_mesh_layer_1_tri_1[];
extern Vtx straight_mushroom_Bone_mesh_layer_1_vtx_2[98];
extern Gfx straight_mushroom_Bone_mesh_layer_1_tri_2[];
extern Gfx mat_straight_mushroom_Material_0_f3d[];
extern Gfx mat_straight_mushroom_Material_1_f3d[];
extern Gfx mat_straight_mushroom_Material_2_f3d[];
extern Gfx straight_mushroom_Bone_mesh_layer_1[];
