extern const GeoLayout fliptile_2_geo[];
extern Lights1 fliptile_2_Material_0_f3d_lights;
extern Lights1 fliptile_2_Material_1_f3d_lights;
extern Lights1 fliptile_2_Material_2_f3d_lights;
extern u8 fliptile_2__0_rgba16[];
extern u8 fliptile_2__1_rgba16[];
extern u8 fliptile_2__2_rgba16[];
extern Vtx fliptile_2_node_mesh_layer_1_vtx_cull[8];
extern Vtx fliptile_2_node_mesh_layer_1_vtx_0[4];
extern Gfx fliptile_2_node_mesh_layer_1_tri_0[];
extern Vtx fliptile_2_node_mesh_layer_1_vtx_1[4];
extern Gfx fliptile_2_node_mesh_layer_1_tri_1[];
extern Vtx fliptile_2_node_mesh_layer_1_vtx_2[16];
extern Gfx fliptile_2_node_mesh_layer_1_tri_2[];
extern Gfx mat_fliptile_2_Material_0_f3d[];
extern Gfx mat_fliptile_2_Material_1_f3d[];
extern Gfx mat_fliptile_2_Material_2_f3d[];
extern Gfx fliptile_2_node_mesh_layer_1[];
