extern const GeoLayout warp_pipe_red_geo[];
extern Lights1 warp_pipe_red_Side_lights;
extern Lights1 warp_pipe_red_Black_lights;
extern Lights1 warp_pipe_red_Top_lights;
extern u8 warp_pipe_red_warp_pipe_side_rgba16_rgba16[];
extern u8 warp_pipe_red_warp_pipe_top_rgba16_rgba16[];
extern Vtx warp_pipe_red_000_displaylist_mesh_layer_1_vtx_0[64];
extern Gfx warp_pipe_red_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx warp_pipe_red_001_displaylist_mesh_layer_1_vtx_0[4];
extern Gfx warp_pipe_red_001_displaylist_mesh_layer_1_tri_0[];
extern Vtx warp_pipe_red_001_displaylist_mesh_layer_1_vtx_1[16];
extern Gfx warp_pipe_red_001_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_warp_pipe_red_Side[];
extern Gfx mat_warp_pipe_red_Black[];
extern Gfx mat_warp_pipe_red_Top[];
extern Gfx warp_pipe_red_000_displaylist_mesh_layer_1[];
extern Gfx warp_pipe_red_001_displaylist_mesh_layer_1[];
extern Gfx warp_pipe_red_material_revert_render_settings[];
