extern const GeoLayout warp_pipe_red_geo[];
extern Lights1 warp_pipe_red_Material_0_f3d_lights;
extern Lights1 warp_pipe_red_Material_1_f3d_lights;
extern Lights1 warp_pipe_red_f3dlite_material_lights;
extern u8 warp_pipe_red__0_i8[];
extern u8 warp_pipe_red__1_i8[];
extern Vtx warp_pipe_red_Bone_mesh_layer_1_vtx_0[64];
extern Gfx warp_pipe_red_Bone_mesh_layer_1_tri_0[];
extern Vtx warp_pipe_red_Bone_mesh_layer_1_vtx_1[16];
extern Gfx warp_pipe_red_Bone_mesh_layer_1_tri_1[];
extern Vtx warp_pipe_red_Bone_mesh_layer_1_vtx_2[4];
extern Gfx warp_pipe_red_Bone_mesh_layer_1_tri_2[];
extern Gfx mat_warp_pipe_red_Material_0_f3d[];
extern Gfx mat_warp_pipe_red_Material_1_f3d[];
extern Gfx mat_warp_pipe_red_f3dlite_material[];
extern Gfx warp_pipe_red_Bone_mesh_layer_1[];
