extern const GeoLayout battery_powerup_geo[];
extern Lights1 battery_powerup_Material_0_f3d_lights;
extern Lights1 battery_powerup_Material_1_f3d_lights;
extern Lights1 battery_powerup_Material_2_f3d_lights;
extern u8 battery_powerup__0_rgba16[];
extern u8 battery_powerup__1_rgba16[];
extern u8 battery_powerup__2_rgba16[];
extern Vtx battery_powerup_node_mesh_layer_1_vtx_cull[8];
extern Vtx battery_powerup_node_mesh_layer_1_vtx_0[43];
extern Gfx battery_powerup_node_mesh_layer_1_tri_0[];
extern Vtx battery_powerup_node_mesh_layer_1_vtx_1[24];
extern Gfx battery_powerup_node_mesh_layer_1_tri_1[];
extern Vtx battery_powerup_node_mesh_layer_1_vtx_2[18];
extern Gfx battery_powerup_node_mesh_layer_1_tri_2[];
extern Gfx mat_battery_powerup_Material_0_f3d[];
extern Gfx mat_battery_powerup_Material_1_f3d[];
extern Gfx mat_battery_powerup_Material_2_f3d[];
extern Gfx battery_powerup_node_mesh_layer_1[];
