extern const GeoLayout curved_mushroom_geo[];
extern Lights1 curved_mushroom_Material_0_f3d_lights;
extern Lights1 curved_mushroom_Material_1_f3d_lights;
extern Lights1 curved_mushroom_Material_2_f3d_lights;
extern u8 curved_mushroom__0_rgba16[];
extern u8 curved_mushroom__1_rgba16[];
extern u8 curved_mushroom__2_rgba16[];
extern Vtx curved_mushroom_Bone_mesh_layer_1_vtx_0[126];
extern Gfx curved_mushroom_Bone_mesh_layer_1_tri_0[];
extern Vtx curved_mushroom_Bone_mesh_layer_1_vtx_1[60];
extern Gfx curved_mushroom_Bone_mesh_layer_1_tri_1[];
extern Vtx curved_mushroom_Bone_mesh_layer_1_vtx_2[98];
extern Gfx curved_mushroom_Bone_mesh_layer_1_tri_2[];
extern Gfx mat_curved_mushroom_Material_0_f3d[];
extern Gfx mat_curved_mushroom_Material_1_f3d[];
extern Gfx mat_curved_mushroom_Material_2_f3d[];
extern Gfx curved_mushroom_Bone_mesh_layer_1[];
