extern const GeoLayout flip_block_geo[];
extern Lights1 flip_block_Flip_Block_lights;
extern u8 flip_block_FlipBlock_rgba16[];
extern Vtx flip_block_smw_block_Bone_mesh_layer_1_mesh_mesh_layer_1_vtx_cull[8];
extern Vtx flip_block_smw_block_Bone_mesh_layer_1_mesh_mesh_layer_1_vtx_0[24];
extern Gfx flip_block_smw_block_Bone_mesh_layer_1_mesh_mesh_layer_1_tri_0[];
extern Gfx mat_flip_block_Flip_Block[];
extern Gfx flip_block_smw_block_Bone_mesh_layer_1_mesh_mesh_layer_1[];
