name: Upload Zip to Discord

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  webhook: https://discord.com/api/webhooks/1240425552700248176/8cIEptH9zF_Guhn3qmG5RgaidwlNTks0JDanM6sgt6jDgc4Bv6TRikuhf1QKWuWrO-uN
  version: us

  major: 0
  milestone: 0
  commit: ${{github.run_number}}

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Create a ZIP file of the repository
      run: |
        zip -r output.zip .

    - name: Compress the ZIP file with 7zip
      run: |
        7z a -tzip output.zip output.zip

    - name: Compress the ZIP file again with gzip
      run: |
        gzip output.zip

    - name: Rename the compressed ZIP file
      run: |
        mv output.zip.gz output.zip
        
    - name: Push build to Discord webhook
      uses: MineBartekSA/discord-webhook@v2
      with:
        webhook: ${{env.webhook}}
        content: |
          New commit: ${{github.event.head_commit.message}} (sha: ${{github.event.after}})
        attachment: |
          file: output.zip
