name: Upload Zip to Discord

on:
  push:
    branches: [ main ]

jobs:
  upload-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create zip file
        run: |
          zip -r repository.zip .

      - name: Upload zip file to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: |
          curl -X POST \
            $DISCORD_WEBHOOK_URL \
            -H 'Content-Type: application/octet-stream' \
            -T repository.zip

      - name: Upload zip file
        uses: actions/download-artifact@1.0.4
        with:
          name: repository.zip
          path: repository.zip

      - name: Clean up
        run: |
          rm repository.zip
